export const PROTECTED_PAGE_PREFIXES = [
  "/dashboard",
  "/settings",
  "/organizations",
  "/chat",
  "/workflows",
  "/agents",
  "/knowledge",
  "/notifications",
  "/posts",
  "/calendar",
  "/reviews",
  "/locations",
  "/integrations",
  "/analytics",
  "/magic-qr",
  "/invite",
] as const;
